bundler_args: ""
script: "bundle exec rake spec"
branches:
  only: master
rvm:
- 2.4
- 2.5
- 2.6
gemfile:
- gemfiles/activerecord_4.2.gemfile
- gemfiles/activerecord_5.2.gemfile
- gemfiles/activerecord_6.0.gemfile
- gemfiles/activerecord_6.1.gemfile
